ignore:
  - "BTW-Project/BTW-Application/*"  #ignore user UI code
  - "BTW-Project/BTW-Graphics/*" #ignore map gui code
  - "BTW-Project/BTW-DataBase/src/main/java/il/ac/technion/cs/yp/btw/db/WeightsDataBase.java" #ignore unused DB
  - "BTW-Project/BTW-DataBase/src/main/java/il/ac/technion/cs/yp/btw/db/StreetsDataBase.java" #ignore unused DB
  - "BTW-Project/BTW-DataBase/src/main/java/il/ac/technion/cs/yp/btw/db/CrossRoadsDataBase.java" #ignore unused DB
  - "BTW-Project/BTW-DataBase/src/main/java/il/ac/technion/cs/yp/btw/db/CentralLocationsDataBase.java" #ignore unused DB
  - "BTW-Project/BTW-DataBase/src/main/java/il/ac/technion/cs/yp/btw/db/queries/QueryAllCentralLocations.java" #ignore unused DB
  - "BTW-Project/BTW-DataBase/src/main/java/il/ac/technion/cs/yp/btw/db/queries/QueryAllStreetNames.java" #ignore unused DB
  - "BTW-Project/BTW-DataBase/src/main/java/il/ac/technion/cs/yp/btw/db/queries/QueryAllTrafficLightPositions.java" #ignore unused DB
  - "BTW-Project/BTW-DataBase/src/main/java/il/ac/technion/cs/yp/btw/db/queries/QueryCentralLocation.java" #ignore unused DB
  - "BTW-Project/BTW-DataBase/src/main/java/il/ac/technion/cs/yp/btw/db/queries/QueryCrossRoad.java" #ignore unused DB
  - "BTW-Project/BTW-DataBase/src/main/java/il/ac/technion/cs/yp/btw/db/queries/QueryOverloadOfRoad.java" #ignore unused DB
  - "BTW-Project/BTW-DataBase/src/main/java/il/ac/technion/cs/yp/btw/db/queries/QueryOverloadOfTrafficLight.java" #ignore unused DB
  - "BTW-Project/BTW-DataBase/src/main/java/il/ac/technion/cs/yp/btw/db/queries/QueryRoad.java" #ignore unused DB
  - "BTW-Project/BTW-DataBase/src/main/java/il/ac/technion/cs/yp/btw/db/queries/QueryStreet.java" #ignore unused DB
  - "BTW-Project/BTW-DataBase/src/main/java/il/ac/technion/cs/yp/btw/db/queries/QueryTrafficLight.java" #ignore unused DB
  - "BTW-Project/BTW-DataBase/src/main/java/il/ac/technion/cs/yp/btw/db/queries/UpdateOverloadOfRoad.java" #ignore unused DB
  - "BTW-Project/BTW-GeoJson/src/main/java/il/ac/technion/cs/yp/btw/geojson/*" #ignore code which uses files for tests
  - "BTW-Project/BTW-CitySimulation/src/main/java/il/ac/technion/cs/yp/btw/citysimulation/JsonVehiclesParser.java" #ignore code which uses files for tests
